### ISSUE TITLE
Roadmap for Version 0.2.0

### ISSUE THREAD

**Issue by herzogmatthias** [velo-org/velo#2]
## Working
- [x] event when a key expires
- [x] event for setting a key
- [x] event for deleting a key
- [x] event for clearing the cache
- [x] stats for different caches
